version: "3.8"
services:
  db:
    image: "postgres:13.4"
    restart: always
    environment:
      POSTGRES_DB: digital_learn_training_db
      POSTGRES_USER: digital_learn_training
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    logging:
      driver: none
  web:
    build:
      context: ../
      args:
        RAILS_ENV: development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      POSTGRES_USER: digital_learn_training
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
    volumes:
      - ../:/rails-app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - "db"
volumes:
  db:
  bundle:
