inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/migrate/**/*"
    - "db/schema.rb"
    - "config/**/*"
    - "script/**/*"

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/AlignArray:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/ModuleLength:
  Max: 110
  Exclude:
    - "spec/controllers/users/buyers_requests_controller_spec.rb" # Just a spec file, it's fine.

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 75
  Exclude:

Metrics/CyclomaticComplexity:
  Max: 17

Metrics/PerceivedComplexity:
  Max: 17

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Exclude:

Rails/Output:
  Exclude:
    - "db/seeds.rb"

Rails/OutputSafety:
  Exclude:
    - "app/helpers/application_helper.rb"

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/RedundantSelf:
  Enabled: false

Style/PercentLiteralDelimiters:
  Exclude:

Style/RegexpLiteral:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false
