variable "vpc_id" {}
variable "region" {}
variable "environment_name" {}
variable "load_balancer_sg_id" {}
variable "bastian_sg_id" {}
variable "db_host" {}
variable "db_username" {}
variable "db_password" {}
variable "instance_type" {}
variable "public_subnet_a_id" {}
variable "public_subnet_b_id" {}
variable "load_balancer_name" {}
variable "lb_target_group_arn" {}
variable "ssh_key_name" {}
